### ISSUE TITLE
Issues keycloak and access to master

### ISSUE THREAD

**Issue by fbianco** [openremote/fleet-management#22]
Hi
I followed the quick start and tutorial (just had to use docker compose instead of docker-compose). I tried it on a remote server running Server 22.04 LTS with a FQDM and on Docker Desktop on Windows 10. In both cases I get running images, but cannot login or do anything with the fleet-management. There are errors loading parts in the dev tools:
![image](https://github.com/openremote/fleet-management/assets/1819057/83bd8a47-36fc-42b6-a045-9fcd5e3a2a45)

![image](https://github.com/openremote/fleet-management/assets/1819057/761029c8-2567-4cd7-bd83-7206d3e1f63b)

I tried to install openremote images to see if the issue was on my side. But this one works as expected:
![image](https://github.com/openremote/fleet-management/assets/1819057/3f92ed32-286f-4a60-b76a-a28c282af375)

![image](https://github.com/openremote/fleet-management/assets/1819057/2036d459-bb86-4f4c-979c-639f4659fd17)

Is there a known issue? which logs could I check to get what's going wrong?

**Comment by pankalog** [comment]
Good afternoon @fbianco!

As you may know, this repo relies on the main OpenRemote repository for a lot of its functionality. I do need to make some adjustments for this repository to work with the latest version of OpenRemote (Keycloak and everything). I'll let you know when it starts working again, but I didn't know it didn't work. Thanks for letting me know!

**Comment by fbianco** [comment]
Hi Pankalog
Thanks for your prompt reply. If I can help providing logs or anything let me know.
BTW I noticed that in the tutorial there the information about the MQTT port to use for the remote device is missing (however visible on the image). Looking forward to test openfleet.
Regards
F

**Comment by pankalog** [comment]
Hello @fbianco ,

Happy to let you know that the app is fixed! I just tried it on my own VPS with the most recent OpenRemote images and everything worked. Let me know if you have any issues!

Panos

**Comment by fbianco** [comment]
Hi pakalog,

Thanks for letting me know.

I just tried again from scratch the quickstart (as on wiki) on an ubuntu server and the quickstart (as in readme) on windows.  I have only access on both settings to the new docker compose extension (not to docker-compose).

On ubuntu the .yml from **blob** file return this error with docker compose : yaml: line 205: mapping values are not allowed in this context. I then switched to the file in **raw** and it worked to setup the images with docker compose.

On both settings all the images are running but I get the same error that keycloak as in my first message.
I might be missing some steps... what shall I set up more that it not stated in the quickstarts?

ubuntu Server 22.04 LTS : Docker version 25.0.3, build 4debf41
windows 11 23H2:  Docker desktop 4.27.2 (137060)

Cheers
F

**Comment by pankalog** [comment]
Good morning @fbianco ,

I am not sure I'm understanding what your issue currently is. You're saying that you're being redirected to login as shown on your first image in this issue? About the blob file link in the Quickstart guide, that has been fixed, thanks for noticing! And what exactly do you mean by `the new docker compose extension`? I'm guessing you're referring that you're using `docker compose` instead of `docker-compose`? 

First of all, to deal with the keycloak issue, I'd first try to remove all the volumes related to the fleet management docker compose project. I'd then do a `docker compose pull` to pull all images from Docker Hub again. Please try out those two and let me know.

Thanks!

PS: Just to speed up the process, if this fails, please send the docker-compose up logs on your next reply

**Comment by fbianco** [comment]
Good morning

Thanks for your prompt reply which solved my issue!

I through that the "docker-compose -p fleet-management up -d" would automatically pulled the last image... I reset it all and did the docker compose pull, now it works. Sorry for bothering you.

Cheers

**Comment by pankalog** [comment]
@fbianco great! Let me know if there are any other issues!
